ALTER SESSION SET "_Oracle_Script"=TRUE;

CREATE USER DSY2201
IDENTIFIED BY "ActForm.DSY"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, RESOURCE TO DSY2201;

ALTER USER DSY2201 
DEFAULT ROLE RESOURCE;